export const defaultTheme = {
  colorMainForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#e6e6e6",
  colorForAboutBackground: "#d8ecfe",
  colorBlue: "#c4e2ff",
  backgroundColorForFarmAdvantage: "#e1edce",
  backgroundColorForShopAdvantage: "#f8ddd7",
  colorForFarmProduct: "#88aa4d",
  colorForShopProduct: "#f75531",
  colorForButton: "#fc9b27",
  colorForButtonHover: "#fc7427",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  lineHeightDefault: "27px",
  pageWidth: "1280px",
};
